### ISSUE TITLE
安装不上

### ISSUE THREAD

**Issue by ruzhefeiyu** [yifoo/Website_navigation#4]
npm run dev这个步骤不行，一直安装不上，没有server/config就链接不上数据

**Comment by yifoo** [comment]
你的Redis和数据库应该没有配置好

**Comment by yifoo** [comment]
> npm run dev这个步骤不行，一直安装不上，没有server/config就链接不上数据

你的Redis和数据库应该没有配置好

**Comment by yifoo** [comment]
> npm run dev这个步骤不行，一直安装不上，没有server/config就链接不上数据

兄弟不好意思，才发现没有上传config，已经补上
